CREATE TABLE "b02_category"(
    "id_category" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY, 
    "tx_name" VARCHAR(255) NOT NULL, 
    PRIMARY KEY("id_category")
);

CREATE TABLE "bg01_blog" (
    "id_blog" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "tx_title" VARCHAR(255) NOT NULL,
    "tx_content" VARCHAR(255) NOT NULL,
    "fk_id_category" INTEGER,
    "fh_created_at" TIMESTAMP NOT NULL,
    "fh_last_update" TIMESTAMP NOT NULL,
    PRIMARY KEY("id_blog") 
);

CREATE TABLE "bg03_tag" (
    "id_tag" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY, 
    "tx_name" VARCHAR(255) NOT NULL,
    PRIMARY KEY("id_tag")
);

CREATE TABLE "bg04_blog_tag" (
    "id_blog_tag" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "fk_id_blog" INTEGER NOT NULL,
    "fk_id_tag" INTEGER NOT NULL,
    PRIMARY KEY("id_blog_tag")
);

ALTER TABLE "bg01_blog"
ADD FOREIGN KEY("fk_id_category") REFERENCES "b02_category"("id_category")
ON UPDATE NO ACTION ON DELETE NO ACTION; 

ALTER TABLE "bg04_blog_tag"
ADD FOREIGN KEY("fk_id_blog") REFERENCES "bg01_blog"("id_blog")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "bg04_blog_tag"
ADD FOREIGN KEY("fk_id_tag") REFERENCES "bg03_tag"("id_tag")
ON UPDATE NO ACTION ON DELETE NO ACTION; 


